export class Worksheet {
  constructor(
    // First section
    public assayNumber,
    public scientist,
    public date,
    public worksheetID,

    // Second section
    public step2_CoatingBuffer,
    public step2_Supplier_1,
    public step2_CoatingBufferLotNumber,
    public step2_CoatingMaterial1,
    public step2_Supplier_2,
    public step2_Concentration_1,
    public step2_CoatingMaterial1LotNumber,
    public step2_ulCoatingMaterial,
    public step2_ulCoatingBuffer,
    public step2_ulCoatingMaterial_ulCoatingBuffer,
    public step2_CheckedBox_1,
    public step2_CheckedBox_2,
    public step2_Time,

    // Third section
    public step3_Item_1,
    public step3_Supplier_1,
    public step3_LotNum,
    public step3_CheckedBox_1,
    public step3_CheckedBox_2,
    public step3_Time,

    // Fourth section
    public step4_Item_1,
    public step4_Supplier_1,
    public step4_LotNum,
    public step4_CheckedBox_1,

    // Fifth Section
    public step5_Item_1,
    public step5_Supplier_1,
    public step5_LotNum,
    public step5_CloneId_1,
    public step5_ulClone_1,
    public step5_ulClone_2,
    public step5_ulDiluent,
    public step5_CheckedBox_1,
    public step5_CheckedBox_2,
    public step5_Time,

    // Sixth Section
    public step6_Item_1,
    public step6_Supplier_1,
    public step6_LotNum,
    public step6_Item_2,
    public step6_Supplier_2,
    public step6_Concentration_1,
    public step6_LotNum_1,
    public step6_ulAvastin,
    public step6_ulSuperblock,
    public step6_Results,
    public step6_ulAvastin1,
    public step6_addingAmount,
    public step6_ulSuperblock_2,
    public step6_Results_2,
    public step6_Item_3,
    public step6_Concentration_2,
    public step6_Concentration_LotNum,
    public step6_ulBiosimilar,
    public step6_ulSuperblock_3,
    public step6_Results_3,
    public step6_ulBiosimilar2,
    public step6_addingAmount_2,
    public step6_Superblock4,
    public step6_Results_4,
    public step6_Item_4,
    public step6_Supplier_4,
    public step6_Concentration_3,
    public step6_LotNum_2,
    public step6_ulStandard,
    public step6_ulSuperblock_5,
    public step6_Results_5,
    public step6_ulStandard2,
    public step6_addingAmount_3,
    public step6_ulSuperblock6,
    public step6_Results_6,
    public step6_Supplier_3,
    public step6_CheckedBox_1,
    public step6_CheckedBox_2,
    public step6_Time,

    // Seventh Section
    public step7_Item_1,
    public step7_Supplier_1,
    public step7_CoatingMaterial0,
    public step7_CheckedBox_1,

    // Eigth Section
    public step8_Item_1,
    public step8_Supplier_1,
    public step8_LotNum,
    public step8_ulConjugate,
    public step8_Item_2,
    public step8_Supplier_2,
    public step8_LotNum_1,
    public step8_Results,
    public step8_ulAmount,
    public step8_ulDiluent,
    public step8_ulDiluent_1,
    public step8_Results_1,
    public step8_addingAmount,
    public step8_CheckedBox_1,
    public step8_CheckedBox_2,
    public step8_Time,

    public step9_Item_1,
    public step9_Supplier_1,
    public step9_LotNum,
    public step9_CheckedBox_1,

    public step10_Item_1,
    public step10_Item_2,
    public step10_Supplier_1,
    public step10_Supplier_2,
    public step10_LotNum,
    public step10_LotNum_1,
    public step10_ulDetection,
    public step10_ulDiluent,
    public step10_Results,
    public step10_ulDectection1,
    public step10_addingAmount,
    public step10_ulDiluent1,
    public step10_Results_1,
    public step10_CheckedBox_1,
    public step10_CheckedBox_2,
    public step10_Time,

    public step11_Item_1,
    public step11_Supplier_1,
    public step11_LotNum,
    public step11_CheckedBox_1,

    public step12_Item_1,
    public step12_Supplier_1,
    public step12_LotNum,
    public step12_TimeInput,
    public step12_CheckedBox_1,
    public step12_CheckedBox_2,
    public  step12_Time,

    public step13_Item_1,
    public step13_Supplier_1,
    public step13_LotNum,
    public step13_CheckedBox_1,
    public step13_CheckedBox_2,

    public status,
    public templateCategory = 1
  ) {}
  // tslint:disable-next-line:member-ordering
  public static Worksheet(w: Worksheet) {
    // @ts-ignore
    return new Worksheet(
      // First Section
      w.assayNumber,
      w.scientist,
      w.date,
      w.worksheetID,

      // Second section
      w.step2_CoatingBuffer,
      w.step2_Supplier_1,
      w.step2_CoatingBufferLotNumber,
      w.step2_CoatingMaterial1,
      w.step2_Supplier_2,
      w.step2_Concentration_1,
      w.step2_CoatingMaterial1LotNumber,
      w.step2_ulCoatingMaterial,
      w.step2_ulCoatingBuffer,
      w.step2_ulCoatingMaterial_ulCoatingBuffer,
      w.step2_CheckedBox_1,
      w.step2_CheckedBox_2,
      w.step2_Time,

      // Third section
      w.step3_Item_1,
      w.step3_Supplier_1,
      w.step3_LotNum,
      w.step3_CheckedBox_1,
      w.step3_CheckedBox_2,
      w.step3_Time,

      // Fourth section
      w.step4_Item_1,
      w.step4_Supplier_1,
      w.step4_LotNum,
      w.step4_CheckedBox_1,

      // Fifth Section
      w.step5_Item_1,
      w.step5_Supplier_1,
      w.step5_LotNum,
      w.step5_CloneId_1,
      w.step5_ulClone_1,
      w.step5_ulClone_2,
      w.step5_ulDiluent,
      w.step5_CheckedBox_1,
      w.step5_CheckedBox_2,
      w.step5_Time,

      // Sixth Section
      w.step6_Item_1,
      w.step6_Supplier_1,
      w.step6_LotNum,
      w.step6_Item_2,
      w.step6_Supplier_2,
      w.step6_Concentration_1,
      w.step6_LotNum_1,
      w.step6_ulAvastin,
      w.step6_ulSuperblock,
      w.step6_Results,
      w.step6_ulAvastin1,
      w.step6_addingAmount,
      w.step6_ulSuperblock_2,
      w.step6_Results_2,
      w.step6_Item_3,
      w.step6_Concentration_2,
      w.step6_Concentration_LotNum,
      w.step6_ulBiosimilar,
      w.step6_ulSuperblock_3,
      w.step6_Results_3,
      w.step6_ulBiosimilar2,
      w.step6_addingAmount_2,
      w.step6_Superblock4,
      w.step6_Results_4,
      w.step6_Item_4,
      w.step6_Supplier_4,
      w.step6_Concentration_3,
      w.step6_LotNum_2,
      w.step6_ulStandard,
      w.step6_ulSuperblock_5,
      w.step6_Results_5,
      w.step6_ulStandard2,
      w.step6_addingAmount_3,
      w.step6_ulSuperblock6,
      w.step6_Results_6,
      w.step6_Supplier_3,
      w.step6_CheckedBox_1,
      w.step6_CheckedBox_2,
      w.step6_Time,

      // Step 7
      w.step7_Item_1,
      w.step7_Supplier_1,
      w.step7_CoatingMaterial0,
      w.step7_CheckedBox_1,

      // Step 8
      w.step8_Item_1,
      w.step8_Supplier_1,
      w.step8_LotNum,
      w.step8_ulConjugate,
      w.step8_Item_2,
      w.step8_Supplier_2,
      w.step8_LotNum_1,
      w.step8_Results,
      w.step8_ulAmount,
      w.step8_ulDiluent,
      w.step8_ulDiluent_1,
      w.step8_Results_1,
      w.step8_addingAmount,
      w.step8_CheckedBox_1,
      w.step8_CheckedBox_2,
      w.step8_Time,

      // Section 9
      w.step9_Item_1,
      w.step9_Supplier_1,
      w.step9_LotNum,
      w.step9_CheckedBox_1,

      // Section 10
      w.step10_Item_1,
      w.step10_Item_2,
      w.step10_Supplier_1,
      w.step10_Supplier_2,
      w.step10_LotNum,
      w.step10_LotNum_1,
      w.step10_ulDetection,
      w.step10_ulDiluent,
      w.step10_Results,
      w.step10_ulDectection1,
      w.step10_addingAmount,
      w.step10_ulDiluent1,
      w.step10_Results_1,
      w.step10_CheckedBox_1,
      w.step10_CheckedBox_2,
      w.step10_Time,

      // Section 11
      w.step11_Item_1,
      w.step11_Supplier_1,
      w.step11_LotNum,
      w.step11_CheckedBox_1,

      // Section 12
      w.step12_Item_1,
      w.step12_Supplier_1,
      w.step12_LotNum,
      w.step12_TimeInput,
      w.step12_CheckedBox_1,
      w.step12_CheckedBox_2,
      w.step12_Time,

      // Section 13
      w.step13_Item_1,
      w.step13_Supplier_1,
      w.step13_LotNum,
      w.step13_CheckedBox_1,
      w.step13_CheckedBox_2,
      w.status,
      w.templateCategory
    );
  }
}

// tslint:disable-next-line:class-name
export class Worksheet_Three {
  constructor(
    // First Section
    public assayNumber,
    public scientist,
    public date: Date,
    public worksheetID: number,
    // End of First Section


    // Section 2
    public step2_Item_1,
    public step2_Supplier_1,
    public step2_LotNum,
    public step2_ConcentrationAmount,

    public step2_Item_2,
    public step2_Supplier_2,
    public step2_LotNum_1,
    public step2_ulCoatingMaterial,
    public step2_ulCoatingBuffer,
    public step2_Results_0,
    public step2_ulCoatingMaterial_0,
    public step2_CoatingMaterial_0,
    public step2_ulCoatingMaterial_ulCoatingBuffer,
    public step2_ulCoatingBuffer_1,
    public step2_CoatingMaterial_2,
    public step2_CoatingMaterial_3,
    public step2_CoatingMaterial_4,
    public step2_ulCoatingMaterial_1,
    public step2_ulCoatingMaterial_2,
    public step2_CoatingMaterial_5,
    public step2_CoatingMaterial_6,
    public step2_ulCoatingBuffer_2,


    public step2_Item_3,
    public step2_Supplier_3,
    public step2_ConcentrationAmount_1,
    public step2_ConcentrationLotNum,
    public step2_ulCoatingMaterial_3,
    public step2_CoatingMaterial_7,
    public step2_Results,
    public step2_ulCoatingMaterial_4,
    public step2_CoatingMaterial_8,
    public step2_ulCoatingBuffer_3,
    public step2_Results_2,

    public step2_Item_9,
    public step2_Supplier_9,
    public step2_Concentration_2,
    public step2_LotNum_2,
    public step2_CoatingMaterial_9,
    public step2_ulCoatingBuffer_4,
    public step2_Results_3,
    public step2_CoatingMaterial_10,
    public step2_CoatingMaterial_11,
    public step2_ulCoatingBuffer_5,
    public step2_Results_4,


    public step2_Item_4,
    public step2_Supplier_4,
    public step2_Concentration_3,
    public step2_LotNum_3,
    public step2_CoatingMaterial_25,
    public step2_ulCoatingBuffer_14,
    public step2_Results_13,
    public step2_CoatingMaterial_26,
    public step2_CoatingMaterial_27,
    public step2_CoatingBuffer_15,
    public step2_Results_14,


    public step2_Item_5,
    public step2_Supplier_5,
    public step2_Concentration_7,
    public step2_LotNum_4,
    public step2_CoatingMaterial_12,
    public step2_ulCoatingBuffer_6,
    public step2_Results_5,
    public step2_CoatingMaterial_13,
    public step2_CoatingMaterial_14,
    public step2_CoatingBuffer_7,
    public step2_Results_6,

    public step2_Item_6,
    public step2_Supplier_6,
    public step2_Concentration_4,
    public step2_LotNum_5,
    public step2_CoatingMaterial_15,
    public step2_ulCoatingBuffer_7,
    public step2_Results_7,
    public step2_CoatingMaterial_16,
    public step2_CoatingMaterial_17,
    public step2_CoatingBuffer_8,
    public step2_Results_8,

    public step2_Item_7,
    public step2_Supplier_7,
    public step2_Concentration_5,
    public step2_LotNum_7,
    public step2_CoatingMaterial_19,
    public step2_CoatingBuffer_10,
    public step2_Results_9,
    public step2_CoatingMaterial_20,
    public step2_CoatingMaterial_21,
    public step2_CoatingBuffer_11,
    public step2_Results_10,

    public step2_CheckedBox_1,
    public step2_CheckedBox_2,
    public step2_Time,

    // Section 3
    public step3_Item_1,
    public step3_Supplier_1,
    public step3_LotNum,
    public step3_CheckedBox_1,

    // Section 4
    public step4_Item_1,
    public step4_LotNum,
    public step4_Supplier_1,
    public step4_CheckedBox_1,
    public step4_CheckedBox_2,
    public step4_Time,

    // Section 5
    public step5_Item_1,
    public step5_Supplier_1,
    public step5_LotNum,
    public step5_CheckedBox_1,

    // Section 6
    public step6_Item_1,
    public step6_Supplier_1,
    public step6_LotNum,

    public step6_Item_2,
    public step6_Supplier_2,
    public step6_Concentration,
    public step6_LotNum_2,
    public step6_ulAvastin,
    public step6_ulSuperblock,
    public step6_Results,
    public step6_ulAvastin_1,
    public step6_addingAmount,
    public step6_ulSuperblock_1,
    public step6_Results_1,

    public step6_Item_3,
    public step6_Supplier_3,
    public step6_Concentration_1,
    public step6_LotNum_3,
    public step6_ulNistmAb,
    public step6_ulSuperblock_2,
    public step6_Results_2,
    public step6_ulNistmAb_2,
    public step6_addingAmount_1,
    public step6_ulSuperblock_3,
    public step6_Results_3,

    public step6_Item_4,
    public step6_Supplier_4,
    public step6_Concentration_2,
    public step6_LotNum_4,
    public step6_ulBeavatas,
    public step6_ulSuperblock_4,
    public step6_Results_4,
    public step6_ulBeavatas_1,
    public step6_addingAmount_2,
    public step6_ulSuperblock_5,
    public step6_Results_5,
    public step6_CheckedBox_1,
    public step6_CheckedBox_2,
    public step6_Time,

    // Section 7
    public step7_Item_1,
    public step7_Supplier_1,
    public step7_LotNum,
    public step7_CheckedBox_1,

    // Section 8
    public step8_Item_1,
    public step8_Supplier_1,
    public step8_LotNum,
    public step8_Item_2,
    public step8_Supplier_2,
    public step8_Concentration_1,
    public step8_LotNum_1,
    public step8_ulConjugate,
    public step8_ulDiluent,
    public step8_Results,
    public step8_ulDectection,
    public step8_addingAmount,
    public step8_ulDiluent_1,
    public step8_Results_1,
    public step8_CheckedBox_1,
    public step8_CheckedBox_2,
    public step8_Time,

    // Section 9
    public step9_Item_1,
    public step9_Supplier_1,
    public step9_LotNum,
    public step9_CheckedBox_1,

    // Section 10
    public step10_ItemName,
    public step10_Supplier,
    public step10_LotNum,
    public step10_mlChemicalInput,
    public step10_mlChemicalInput_2,
    public step10_CheckedBox_1,
    public step10_CheckedBox_2,
    public step10_CheckedBox_3,
    public step10_CheckedBox_4,

    public status,
    public templateCategory = 3
  ) {}

  // tslint:disable-next-line:member-ordering
  public static Worksheet_Three(w3: Worksheet_Three): Worksheet_Three {
    return new Worksheet_Three(
      // First Section
      w3.assayNumber,
      w3.scientist,
      w3.date,
      w3.worksheetID,
      // End of First Section
      // Section 2
      w3.step2_Item_1,
      w3.step2_Supplier_1,
      w3.step2_LotNum,
      w3.step2_ConcentrationAmount,

      w3.step2_Item_2,
      w3.step2_Supplier_2,
      w3.step2_LotNum_1,
      w3.step2_ulCoatingMaterial,
      w3.step2_ulCoatingBuffer,
      w3.step2_Results_0,
      w3.step2_ulCoatingMaterial_0,
      w3.step2_CoatingMaterial_0,
      w3.step2_ulCoatingMaterial_ulCoatingBuffer,
      w3.step2_ulCoatingBuffer_1,
      w3.step2_CoatingMaterial_2,
      w3.step2_CoatingMaterial_3,
      w3.step2_CoatingMaterial_4,
      w3.step2_ulCoatingMaterial_1,
      w3.step2_ulCoatingMaterial_2,
      w3.step2_CoatingMaterial_5,
      w3.step2_CoatingMaterial_6,
      w3.step2_ulCoatingBuffer_2,


      w3.step2_Item_3,
      w3.step2_Supplier_3,
        w3.step2_ConcentrationAmount_1,
        w3.step2_ConcentrationLotNum,
        w3.step2_ulCoatingMaterial_3,
        w3.step2_CoatingMaterial_7,
        w3.step2_Results,
      w3.step2_ulCoatingMaterial_4,
      w3.step2_CoatingMaterial_8,
      w3.step2_ulCoatingBuffer_3,
      w3.step2_Results_2,

      w3.step2_Item_9,
      w3.step2_Supplier_9,
      w3.step2_Concentration_2,
      w3.step2_LotNum_2,
      w3.step2_CoatingMaterial_9,
      w3.step2_ulCoatingBuffer_4,
      w3.step2_Results_3,
      w3.step2_CoatingMaterial_10,
      w3.step2_CoatingMaterial_11,
      w3.step2_ulCoatingBuffer_5,
      w3.step2_Results_4,


      w3.step2_Item_4,
      w3.step2_Supplier_4,
      w3.step2_Concentration_3,
        w3.step2_LotNum_3,
        w3.step2_CoatingMaterial_25,
        w3.step2_ulCoatingBuffer_14,
        w3.step2_Results_13,
        w3.step2_CoatingMaterial_26,
        w3.step2_CoatingMaterial_27,
        w3.step2_CoatingBuffer_15,
        w3.step2_Results_14,


      w3.step2_Item_5,
      w3.step2_Supplier_5,
      w3.step2_Concentration_7,
        w3.step2_LotNum_4,
      w3.step2_CoatingMaterial_12,
      w3.step2_ulCoatingBuffer_6,
      w3.step2_Results_5,
      w3.step2_CoatingMaterial_13,
      w3.step2_CoatingMaterial_14,
      w3.step2_CoatingBuffer_7,
      w3.step2_Results_6,

      w3.step2_Item_6,
      w3.step2_Supplier_6,
      w3.step2_Concentration_4,
      w3.step2_LotNum_5,
      w3.step2_CoatingMaterial_15,
      w3.step2_ulCoatingBuffer_7,
      w3.step2_Results_7,
      w3.step2_CoatingMaterial_16,
      w3.step2_CoatingMaterial_17,
      w3.step2_CoatingBuffer_8,
      w3.step2_Results_8,

      w3.step2_Item_7,
      w3.step2_Supplier_7,
      w3.step2_Concentration_5,
      w3.step2_LotNum_7,
      w3.step2_CoatingMaterial_19,
      w3.step2_CoatingBuffer_10,
      w3.step2_Results_9,
      w3.step2_CoatingMaterial_20,
      w3.step2_CoatingMaterial_21,
      w3.step2_CoatingBuffer_11,
      w3.step2_Results_10,


      w3.step2_CheckedBox_1,
      w3.step2_CheckedBox_2,
      w3.step2_Time,

      // Section 3
      w3.step3_Item_1,
      w3.step3_Supplier_1,
      w3.step3_LotNum,
      w3.step3_CheckedBox_1,

      // Section 4
      w3.step4_Item_1,
      w3.step4_LotNum,
      w3.step4_Supplier_1,
      w3.step4_CheckedBox_1,
      w3.step4_CheckedBox_2,
      w3.step4_Time,

      // Section 5
      w3.step5_Item_1,
      w3.step5_Supplier_1,
      w3.step5_LotNum,
      w3.step5_CheckedBox_1,

      // Section 6
      w3.step6_Item_1,
      w3.step6_Supplier_1,
      w3.step6_LotNum,

      w3.step6_Item_2,
      w3.step6_Supplier_2,
      w3.step6_Concentration,
      w3.step6_LotNum_2,
      w3.step6_ulAvastin,
      w3.step6_ulSuperblock,
      w3.step6_Results,
      w3.step6_ulAvastin_1,
      w3.step6_addingAmount,
      w3.step6_ulSuperblock_1,
      w3.step6_Results_1,

      w3.step6_Item_3,
      w3.step6_Supplier_3,
      w3.step6_LotNum_3,
      w3.step6_Concentration_1,
      w3.step6_ulNistmAb,
      w3.step6_ulSuperblock_2,
      w3.step6_Results_2,
      w3.step6_ulNistmAb_2,
      w3.step6_addingAmount_1,
      w3.step6_ulSuperblock_3,
      w3.step6_Results_3,

      w3.step6_Item_4,
      w3.step6_Supplier_4,
      w3.step6_Concentration_2,
      w3.step6_LotNum_4,
      w3.step6_ulSuperblock_4,
      w3.step6_ulBeavatas,
      w3.step6_Results_4,
      w3.step6_ulBeavatas_1,
      w3.step6_addingAmount_2,
      w3.step6_ulSuperblock_5,
      w3.step6_Results_5,
      w3.step6_CheckedBox_1,
      w3.step6_CheckedBox_2,
      w3.step6_Time,

      // Section 7
      w3.step7_Item_1,
      w3.step7_Supplier_1,
      w3.step7_LotNum,
      w3.step7_CheckedBox_1,

      // Section 8
      w3.step8_Item_1,
      w3.step8_Supplier_1,
      w3.step8_LotNum,
      w3.step8_Item_2,
      w3.step8_Supplier_2,
      w3.step8_Concentration_1,
      w3.step8_LotNum_1,
      w3.step8_ulConjugate,
      w3.step8_ulDiluent,
      w3.step8_Results,
      w3.step8_ulDectection,
      w3.step8_addingAmount,
      w3.step8_ulDiluent_1,
      w3.step8_Results_1,
      w3.step8_CheckedBox_1,
      w3.step8_CheckedBox_2,
      w3.step8_Time,

      // Section 9
      w3.step9_Item_1,
      w3.step9_Supplier_1,
      w3.step9_LotNum,
      w3.step9_CheckedBox_1,

      // Section 10
      w3.step10_ItemName,
      w3.step10_Supplier,
      w3.step10_LotNum,
      w3.step10_mlChemicalInput,
      w3.step10_mlChemicalInput_2,
      w3.step10_CheckedBox_1,
      w3.step10_CheckedBox_2,
      w3.step10_CheckedBox_3,
      w3.step10_CheckedBox_4,
      w3.status,
      w3.templateCategory
    );
  }
}

// tslint:disable-next-line:class-name
export class Worksheet_Four {
  constructor(
    // First Section
    public assayNumber,
    public scientist,
    public date: Date,
    public worksheetID,
    // End of First Section

    // Section 2
    public step2_Item_1,
    public step2_Supplier_1,
    public step2_LotNum,
    public step2_Item_2,
    public step2_Supplier_2,
    public step2_Concentration_1,
    public step2_LotNum_1,
    public step2_CoatingMaterial_1,
    public step2_ulCoatingBuffer,
    public step2_Results,
    public step2_ulCoatingMaterial,
    public step2_addingAmount,
    public step2_ulCoatingBuffer_0,
    public step2_Results_1,
    public step2_Item_3,
    public step2_Supplier_3,
    public step2_Concentration_2,
    public step2_LotNum_2,
    public step2_ulCoatingMaterial_1,
    public step2_ulCoatingBuffer_1,
    public step2_Results_2,
    public step2_ulCoatingMaterial_2,
    public step2_addingAmount_1,
    public step2_CoatingBuffer_2,
    public step2_Results_3,

    public step2_Item_4,
    public step2_Supplier_4,
    public step2_Concentration_3,
    public step2_LotNum_4,
    public step2_CoatingMaterial_3,
    public step2_CoatingBuffer_3,
    public step2_Results_4,
    public step2_ulCoatingMaterial_4,
    public step2_addingAmount_2,
    public step2_ulCoatingBuffer_4,
    public step2_Results_5,
    public step2_Item_8,
    public step2_Supplier_8,
    public step2_Concentration_7,
    public step2_LotNum_7,
    public step2_CoatingMaterial_9,
    public step2_CoatingBuffer_8,
    public step2_Results_11,
    public step2_ulCoatingMaterial_8,
    public step2_addingAmount_8,
    public step2_ulCoatingBuffer_10,
    public step2_Results_10,
    public step2_Item_5,
    public step2_Supplier_5,
    public step2_Concentration_4,
    public step2_LotNum_5,
    public step2_ulCoatingMaterial_5,
    public step2_ulCoatingBuffer_5,
    public step2_Results_6,
    public step2_ulCoatingMaterial_6,
    public step2_addingAmount_3,
    public step2_ulCoatingBuffer_6,
    public step2_Results_7,
    public step2_Item_6,
    public step2_Supplier_6,
    public step2_Concentration_5,
    public step2_LotNum_6,
    public step2_CoatingMaterial_7,
    public step2_ulCoatingBuffer_7,
    public step2_Results_8,
    public step2_ulCoatingMaterial_7,
    public step2_addingAmount_4,
    public step2_ulCoatingBuffer_8,
    public step2_Results_9,

    public step2_CheckedBox_1,
    public step2_CheckedBox_2,
    public step2_Time,
    //  Section 3
    public step3_Item_1,
    public step3_Supplier_1,
    public step3_LotNum,
    public step3_CheckedBox_1,
    // Section 4
    public step4_Item_1,
    public step4_Supplier_1,
    public step4_LotNum,
    public step4_CheckedBox_1,
    public step4_CheckedBox_2,
    public step4_Time,
    // Section 5
    public step5_Item_1,
    public step5_Supplier_1,
    public step5_LotNum,
    public step5_CheckedBox_1,
    // Section 6
    public step6_Item_1,
    public step6_Supplier_1,
    public step6_LotNum_1,
    public step6_Item_2,
    public step6_Supplier_2,
    public step6_LotNum_2,
    public step6_Concentration_1,
    public step6_ulAvastin,
    public step6_ulSuperblock,
    public step6_Results,
    public step6_ulAvastin_1,
    public step6_addingAmount,
    public step6_ulSuperblock_1,
    public step6_Results_2,
    public step6_CheckedBox_1,
    public step6_CheckedBox_2,
    public step6_Time,
    // Section 7
    public step7_Item_1,
    public step7_Supplier_1,
    public step7_LotNum_1,
    public step7_Item_2,
    public step7_Supplier_2,
    public step7_LotNum_2,
    public step7_ulConjugate,
    public step7_ulDiluent,
    public step7_ul,
    public step7_Results,
    public step7_addingAmount,
    public step7_ulDiluent_1,
    public step7_Results_1,
    public step7_CheckedBox_1,
    public step7_CheckedBox_2,
    public step7_Concentration_1,
    public step7_Time,
    // Section 8
    public step8_Item_1,
    public step8_Supplier_1,
    public step8_LotNum,
    public step8_CheckedBox_1,
    // Section 9
    public step9_Item_1,
    public step9_Supplier_1,
    public step9_LotNum,
    public step9_CheckedBox_1,
    public step9_mlAmount,
    public step9_mlAmount_1,
    public step9_CheckedBox_2,
    public step9_CheckedBox_3,
    public step9_CheckedBox_4,

    public status,
    public templateCategory = 4
  ) {}

  //
  // tslint:disable-next-line:member-ordering
  public static Worksheet_Four(w4: Worksheet_Four): Worksheet_Four {
    return new Worksheet_Four(
      // First Section
      w4.assayNumber,
      w4.scientist,
      w4.date,
      w4.worksheetID,
      // End of First Section

      // Section 2
        w4.step2_Item_1,
        w4.step2_Supplier_1,
        w4.step2_LotNum,
        w4.step2_Item_2,
        w4.step2_Supplier_2,
        w4.step2_Concentration_1,
        w4.step2_LotNum_1,
        w4.step2_CoatingMaterial_1,
        w4.step2_ulCoatingBuffer,
        w4.step2_Results,
        w4.step2_ulCoatingMaterial,
        w4.step2_addingAmount,
        w4.step2_ulCoatingBuffer_0,
        w4.step2_Results_1,
        w4.step2_Item_3,
        w4.step2_Supplier_3,
        w4.step2_Concentration_2,
        w4.step2_LotNum_2,
        w4.step2_ulCoatingMaterial_1,
        w4.step2_ulCoatingBuffer_1,
        w4.step2_Results_2,
        w4.step2_ulCoatingMaterial_2,
        w4.step2_addingAmount_1,
        w4.step2_CoatingBuffer_2,
        w4.step2_Results_3,

        w4.step2_Item_4,
        w4.step2_Supplier_4,
        w4.step2_Concentration_3,
        w4.step2_LotNum_4,
        w4.step2_CoatingMaterial_3,
        w4.step2_CoatingBuffer_3,
        w4.step2_Results_4,
        w4.step2_ulCoatingMaterial_4,
        w4.step2_addingAmount_2,
        w4.step2_ulCoatingBuffer_4,
        w4.step2_Results_5,
        w4.step2_Item_8,
        w4.step2_Supplier_8,
        w4.step2_Concentration_7,
        w4.step2_LotNum_7,
        w4.step2_CoatingMaterial_9,
        w4.step2_CoatingBuffer_8,
        w4.step2_Results_11,
        w4.step2_ulCoatingMaterial_8,
        w4.step2_addingAmount_8,
        w4.step2_ulCoatingBuffer_10,
        w4.step2_Results_10,
        w4.step2_Item_5,
        w4.step2_Supplier_5,
        w4.step2_Concentration_4,
        w4.step2_LotNum_5,
        w4.step2_ulCoatingMaterial_5,
        w4.step2_ulCoatingBuffer_5,
        w4.step2_Results_6,
        w4.step2_ulCoatingMaterial_6,
        w4.step2_addingAmount_3,
        w4.step2_ulCoatingBuffer_6,
        w4.step2_Results_7,
        w4.step2_Item_6,
        w4.step2_Supplier_6,
        w4.step2_Concentration_5,
        w4.step2_LotNum_6,
        w4.step2_CoatingMaterial_7,
        w4.step2_ulCoatingBuffer_7,
        w4.step2_Results_8,
        w4.step2_ulCoatingMaterial_7,
        w4.step2_addingAmount_4,
        w4.step2_ulCoatingBuffer_8,
        w4.step2_Results_9,
        w4.step2_CheckedBox_1,
      w4.step2_CheckedBox_2,
      w4.step2_Time,

      //  Section 3
      w4.step3_Item_1,
      w4.step3_Supplier_1,
      w4.step3_LotNum,
      w4.step3_CheckedBox_1,

      // Section 4
      w4.step4_Item_1,
      w4.step4_Supplier_1,
      w4.step4_LotNum,
      w4.step4_CheckedBox_1,
      w4.step4_CheckedBox_2,
      w4.step4_Time,

      // Section 5
      w4.step5_Item_1,
      w4.step5_Supplier_1,
      w4.step5_LotNum,
      w4.step5_CheckedBox_1,
      // Section 6
      w4.step6_Item_1,
      w4.step6_Supplier_1,
      w4.step6_LotNum_1,
      w4.step6_Item_2,
      w4.step6_Supplier_2,
      w4.step6_LotNum_2,
      w4.step6_Concentration_1,
      w4.step6_ulAvastin,
      w4.step6_ulSuperblock,
      w4.step6_Results,
      w4.step6_ulAvastin_1,
      w4.step6_addingAmount,
      w4.step6_ulSuperblock_1,
      w4.step6_Results_2,
      w4.step6_CheckedBox_1,
      w4.step6_CheckedBox_2,
      w4.step6_Time,

      // Section 7
      w4.step7_Item_1,
      w4.step7_Supplier_1,
      w4.step7_LotNum_1,
      w4.step7_Item_2,
      w4.step7_Supplier_2,
      w4.step7_LotNum_2,
      w4.step7_ulConjugate,
      w4.step7_ulDiluent,
      w4.step7_ul,
      w4.step7_Results,
      w4.step7_addingAmount,
      w4.step7_ulDiluent_1,
      w4.step7_Results_1,
      w4.step7_CheckedBox_1,
      w4.step7_CheckedBox_2,
      w4.step7_Concentration_1,
      w4.step7_Time,

      // Section 8
      w4.step8_Item_1,
      w4.step8_Supplier_1,
      w4.step8_LotNum,
      w4.step8_CheckedBox_1,

      // Section 9
      w4.step9_Item_1,
      w4.step9_Supplier_1,
      w4.step9_LotNum,
      w4.step9_CheckedBox_1,
      w4.step9_mlAmount,
      w4.step9_mlAmount_1,
      w4.step9_CheckedBox_2,
      w4.step9_CheckedBox_3,
      w4.step9_CheckedBox_4,
      w4.status,
      w4.templateCategory
    );
  }
}

// tslint:disable-next-line:class-name
export class Worksheet_Status {
  constructor(
    public reviewComment,
    public qcComment,
    public status,
    public worksheetID
  ) {}

  public static Worksheet_Status(w5: Worksheet_Status): Worksheet_Status {
    return new Worksheet_Status(
      // First Section
      w5.reviewComment,
      w5.qcComment,
      w5.status,
      w5.worksheetID
    );
  }
}
